/** Shared by the player, CPU and the selection screen. */
export const MACHINES = [
  {
    name: 'スパーク',
    role: 'バランス',
    detail: '迷ったらこれ。速度と旋回のバランス型。',
    speed: 1,
    turn: 1,
    grip: 1,
    boost: 1.65,
    duration: 1,
    charge: 0.85,
  },
  {
    name: 'ソニック',
    role: '最高速',
    detail: '直線が速い。カーブは早めにPUSHで減速。',
    speed: 1.14,
    turn: 0.82,
    grip: 0.95,
    boost: 1.6,
    duration: 0.9,
    charge: 0.95,
  },
  {
    name: 'リーフ',
    role: '旋回',
    detail: '小回りと安定感が得意。最高速は控えめ。',
    speed: 0.9,
    turn: 1.28,
    grip: 1.3,
    boost: 1.6,
    duration: 1,
    charge: 0.85,
  },
  {
    name: 'ボルト',
    role: 'チャージ',
    detail: '通常走行は遅め。素早くためて長くダッシュ！',
    speed: 0.86,
    turn: 1,
    grip: 1,
    boost: 2.05,
    duration: 1.3,
    charge: 0.6,
  },
] as const;
