CONTRACT = {
    "operation_id": "readRoom",
    "slug": "read",
    "method": "GET",
    "path": "/api/rooms/{code}",
    "auth": "member",
    "permission": "member",
    "request": "none",
    "response": "Response",
    "errors": [400, 403, 404, 409, 410, 422, 429, 503],
    "idempotency": "per-player requestId / input seq",
    "transaction": "DynamoDB version CAS",
    "effects": "DynamoDB state then Streams delivery",
    "requirements": ["BR-SEC-001"],
}
